1 review
T-V-N/gopherstore pull request #1
Opened 2022-11-30 18:50 UTC by T-V-N

2022-12-01 08:24 UTC, lostsequence requested changes

2022-12-01 08:24 UTC, lostsequence commented on cmd/gophermart/main.go
> +	st, err := storage.InitStorage(*cfg)
Не нашел где закрывается коннекшн к базе

2022-12-01 08:24 UTC, lostsequence commented on internal/shared_types/shared_types.go
> +}
1. Интерфейс лучше объявить там, где он используется
2. Интерфейс уже немного перегружен. Разнеси интерфейс по зонам ответственности, например, users, withdrawal,  orders. В таком случае и методы будут недоступны там, где они не нужны.
3. На каждый стор будет своя структура со своими методами.

2022-12-01 08:24 UTC, lostsequence commented on internal/app/app.go
> +	if balance.Current-amount < 0 {
Лучше эту проверку перенести в транзакцию, чтобы на момент обновления был актуальный баланс

2022-12-01 08:24 UTC, lostsequence commented on internal/handler/handler.go
> +}
Раздели пожалуйста handler и app на зоны ответственности так же как и стор.

2022-12-01 08:24 UTC, lostsequence commented on cmd/gophermart/main.go
> +	router.Use(chiMw.Compress(5))
эта миддлварь только на сжатие ? на распаковку работает ?

2022-12-01 08:24 UTC, lostsequence commented on cmd/gophermart/main.go
> +	go service.InitUpdater(*cfg, *st, 1)
Попробуй прикрутить NotifyContext, и передать его в горутину/инит базы
Он практически в любом го сервисе будет использоваться в проде.
И на отмену штатно завершить эти процессы и сервер стопануть

2022-12-01 08:24 UTC, lostsequence commented on internal/handler/handler.go
> +	uid, err := h.app.Register(ctx, cred)
Лучше сделать доступ к app тоже через интерфейс

2022-12-01 08:24 UTC, lostsequence commented on internal/services/orderUpdater.go
> +	for i := 0; i < workerLimit; i++ {
Хорошо добавить вейтгруппы для контроля завершения

2022-12-01 08:24 UTC, lostsequence commented on cmd/gophermart/main.go
> +		log.Panic("Unable to load config. Check if it was passed")
Мало логов везде. Добавь пожалуйста логи на ошибки 100% вместо fmt.Ptint. Info логи по желанию :) но тоже полезная штука

2022-12-01 17:06 UTC, T-V-N commented on cmd/gophermart/main.go
> +	st, err := storage.InitStorage(*cfg)
просто закрыть в defere

2022-12-01 17:12 UTC, T-V-N commented on internal/shared_types/shared_types.go
> +}
1. Вместо общего storage interface создать ресурсы-интерфейсы (User, Orders, Withdrawals) 
2. Написать миграции. (опционально) 
3. Вместо одного storage.go сделать разбивку по ресурсам так же и в бд

2022-12-01 17:13 UTC, T-V-N commented on internal/handler/handler.go
> +}
см. коммент со сторами

2022-12-01 17:13 UTC, T-V-N commented on cmd/gophermart/main.go
> +	router.Use(chiMw.Compress(5))
см. комменты по urlshortener

2022-12-01 17:17 UTC, T-V-N commented on internal/services/orderUpdater.go
> +	for i := 0; i < workerLimit; i++ {
см. коммент к NotifyCOntext

2022-12-01 17:17 UTC, T-V-N commented on cmd/gophermart/main.go
> +	go service.InitUpdater(*cfg, *st, 1)
1. почитать про signal notify context golang 
2. По sigterm закончить работу горутины, закрыть конекшон

2022-12-01 17:19 UTC, T-V-N commented on internal/handler/handler.go
> +	uid, err := h.app.Register(ctx, cred)
по аналогии с storage interface (чтобы потом мокать)

2022-12-01 17:21 UTC, T-V-N commented on cmd/gophermart/main.go
> +		log.Panic("Unable to load config. Check if it was passed")
Взять популярный логгер и сгружать в него все ошибки / полезную инфу

2022-12-01 17:23 UTC, T-V-N commented on cmd/gophermart/main.go
> +		log.Panic("Unable to load config. Check if it was passed")
start/stop + залогать работу горутины апдейтера

2022-12-01 17:24 UTC, T-V-N commented
Все magic numbers перевезти в конфиг

2022-12-01 17:25 UTC, T-V-N commented on internal/storage/storage.go
> +func (st *Storage) UpdateOrder(ctx context.Context, orderID, status string, accrual float32) error {
упаковать обе транзакции в одну

2022-12-01 17:31 UTC, T-V-N commented on internal/app/app.go
> +	if balance.Current-amount < 0 {
либо залочить мьютексами юзера

2022-12-01 17:32 UTC, T-V-N commented on internal/app/app.go
> +	if balance.Current-amount < 0 {
map мьютексов с привязкой к юзеру, если юзер не залочен, то списывать можно, если залочен, то нельзя

2022-12-01 17:37 UTC, T-V-N commented on internal/storage/storage.go
> +func (st *Storage) UpdateOrder(ctx context.Context, orderID, status string, accrual float32) error {
либо на слое app сделать мэп локов для юзеров, в которых смотреть не залочен ли юзер перед обновлением

2022-12-01 20:17 UTC, lostsequence commented on internal/services/orderUpdater.go
> +	}
обработай отдельно 429 ошибку
можно взять хедер - retry-after и повторить запрос через это время

2022-12-11 19:28 UTC, lostsequence commented on cmd/gophermart/main.go
> +	go service.InitUpdater(*cfg, st.Conn, cfg.WorkerLimit, sugar, ctx)
контекст принято передавать первым параментром

2022-12-11 19:29 UTC, lostsequence commented on cmd/gophermart/main.go
> +	defer stop()
вызови stop сразу после <-ctx.done(), чтобы вернуть возможность прервать  программу

2022-12-11 19:30 UTC, lostsequence commented on cmd/gophermart/main.go
> +	err = server.Shutdown(context.Background())
добавь контекст с таймаутом

2022-12-11 19:31 UTC, lostsequence commented on internal/app/order.go
> +	}
работу с внешней системой надо вынести в интерфейс, иначе не получится потестировать

2022-12-11 19:39 UTC, lostsequence commented on internal/handler/handler_test.go
> +
тесты хорошо бы тоже разделить по файликам, как и сами хендлеры

2022-12-11 19:43 UTC, lostsequence commented on internal/services/orderUpdater.go
> +			orders, err := order.GetUnproccessedOrders(context.Background())
не используй пустой контекст, можно добавить с таймаутом

2022-12-11 19:47 UTC, lostsequence commented on internal/services/orderUpdater.go
> +		}()
в этом месте не очень понял. если мы делаем паузу в горутине, то поток выполнения не блокируется и мы опять получим too many requests ?

2022-12-11 19:49 UTC, lostsequence commented on internal/services/orderUpdater.go
> +			logger.Info("Workers gracefully stopped")
можно и канал на всякий случай прикрыть

2022-12-11 19:52 UTC, lostsequence commented on cmd/gophermart/main.go
> +	go server.ListenAndServe()
обычно в ListenAndServe еще ошибку обрабатывают

2022-12-11 19:54 UTC, lostsequence commented on cmd/gophermart/main.go
> +	})
может вынести инициализацию роутера в отдельный файлик router.go ?

2022-12-11 20:05 UTC, lostsequence commented on internal/handler/orderHandler.go
> +}
В go не принято писать в названии интерфейса "Interface", обычно стараются использовать какой-нибудь глагол

2022-12-11 20:12 UTC, lostsequence requested changes
поправить комментарии

2022-12-11 20:22 UTC, lostsequence commented on internal/app/user.go
> +	balance, err := app.User.GetBalanceAndLock(ctx, uid)
мютекс лучше на уровне app определить и лочить/анлочит прямо в этот методе с момента получения баланса

2022-12-12 19:47 UTC, T-V-N commented on cmd/gophermart/main.go
> +	})
выглядит не оч, ну допустим

2022-12-12 22:06 UTC, T-V-N commented on cmd/gophermart/main.go
> +	go service.InitUpdater(*cfg, st.Conn, cfg.WorkerLimit, sugar, ctx)
вот тут у меня такие вайбы, как будто я не очень хорошо сделал. Обрати внимание пожалуйста

2022-12-13 14:18 UTC, T-V-N commented on internal/app/user.go
> +	balance, err := app.User.GetBalanceAndLock(ctx, uid)
вот тут момент, у меня лок используется не только в app, но и в сервисе апдейтера, который про app не знает. Я правильно понял, что в этот сервис лучше передать app, чтобы можно было мьютекс на уровне app объявить и не пересоздавать ничего в сервисе?

2022-12-13 15:44 UTC, T-V-N commented on internal/services/orderUpdater.go
> +		}()
Я не понял, как правильно прервать работу сервиса на время. Создать блокирующий канал для всего апдейтера?

2022-12-13 17:42 UTC, lostsequence commented on internal/services/orderUpdater.go
> +		}()
всех воркеров вряд ли можно сразу остановить. можно в конкретном месте просто паузу сделать, но не в горутине

2022-12-13 19:20 UTC, lostsequence commented on internal/app/user.go
> +	balance, err := app.User.GetBalanceAndLock(ctx, uid)
1. можно передать в updater не стор, а app. И в app уже взаимодействовать со сторами и мьютексами (мьютекс там уже есть)
2. создать общий мьютекс в main и передать и в app и в updater

2022-12-13 19:22 UTC, lostsequence commented on cmd/gophermart/main.go
> +	go service.InitUpdater(*cfg, st.Conn, cfg.WorkerLimit, sugar, ctx)
немного не так. например:
```
gr := &sync.WaitGroup{}
gr.Add(1)
go func() {
service.InitUpdater(ctx, *cfg, st.Conn, cfg.WorkerLimit, sugar)
gr.Done()
}()
```

2022-12-15 18:00 UTC, T-V-N commented on internal/app/order.go
> +	}
в структ order добавить поле с orderRegisterer

2022-12-15 18:06 UTC, T-V-N commented on internal/services/orderUpdater.go
> +		}()
привязать checkOrder к воркеру так, чтобы на retry ответе блочился только конкретный воркер, а другие не будут блочиться.

2022-12-15 18:13 UTC, T-V-N commented on internal/app/order.go
> +	Order  sharedTypes.OrderStorage
Добавить сюда userStorage поле

2022-12-15 18:14 UTC, T-V-N commented on internal/app/user.go
> +	Withdrawal sharedTypes.WithdrawalStorage
Сюда добавляем поле orderStorage

2022-12-15 18:15 UTC, T-V-N commented on internal/services/orderUpdater.go
> +		err = u.order.UpdateOrder(ctx, orderID, o.Status, o.Accrual, u.user)
вызывать Update через orderApp, сначала апдейтим ордер, потом апдейтим юзера
сделать отдельный лок здесь

2022-12-15 18:18 UTC, T-V-N commented on internal/services/orderUpdater.go
> +		err = u.order.UpdateOrder(ctx, orderID, o.Status, o.Accrual, u.user)
Сделать map мьютексов на уровне main. Сделать так, чтобы updater и order блочили эти мьютексы перед записью.

2022-12-20 19:25 UTC, lostsequence approved these changes

2023-05-17 08:11 UTC, merged